spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    discovery:
      locator:
        enabled: true
    gateway:
      routes:
        # ?? ?? ??

server:
  port: 8072
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8900/eureka
