spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: ORDER-COMMAND-SERVICE
          uri: lb://ORDER-COMMAND-SERVICE
          predicates:
            - Path=/orders/**
            - Method=POST,PUT,DELETE
        - id: item-service
          uri: lb://ITEM-SERVICE
          predicates:
            - Path=/items/**

server:
  port: 8072
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8900/eureka
