version: '3'
services:
  database:
    image: 'mysql:latest'
    container_name: order_database
    restart: always
    ports:
      - '3307:3307'
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4 # utf8 for kor
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root # 데이터 보존 계획이 없으므로 편의를 위하여 비밀번호 노출
      MYSQL_DATABASE: orders
      MYSQL_TCP_PORT: 3307
