version: '3'
services:
  database:
    image: 'mysql:latest'
    container_name: joo_noti_database
    restart: always
    ports:
      - '3308:3308'
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4 # utf8 for kor
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root # 데이터 보존 계획이 없으므로 편의를 위하여 비밀번호 노출
      MYSQL_DATABASE: notification_log
      MYSQL_TCP_PORT: 3308

  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
