server:
  port: 9100

spring:
  application:
    name: ORDER-COMMAND-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3307/orders?useSSL=false&serverTimezone=Asia/Seoul"
    username: root
    password: root
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8900/eureka