version: '3'
services:
  database:
    image: 'mysql:latest'
    container_name: item_database
    restart: always
    ports:
      - '3306:3306'
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4 # utf8 for kor
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root # 데이터 보존 계획이 없으므로 편의를 위하여 비밀번호 노출
      MYSQL_DATABASE: item
#    volumes:
#      -
  mongodb:
    image: 'mongo:latest'
    container_name: item_query_cache
    restart: always
    ports:
      - '27017:27017'
#    volumes:
#      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=item_query_cache

