version: '3.8'
services:
  database:
    image: mysql:8.0.30
    container_name: order_database
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
#      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - '3307:3306'
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4 # utf8 for kor
      - --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=orders
      - MYSQL_USER=local
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Seoul
