server:
  port: 8081

spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/item?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&useSSL=false'
    username: root
    password: root
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  data:
    mongodb:
      username: root
      password: root
      uri: 'mongodb://root:root@localhost:27017/item_query_cache?authSource=admin'
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8900/eureka

external:
